version: "3"
services:
  taurus-manager:
    hostname: taurus-manager
    container_name: taurus-manager
    build: docker
    ports:
      - "8001:8001"
    expose:
      - 8001
    volumes:
      - ./:/opt/taurus
    restart: always
